### ISSUE TITLE
Alignment bug

### ISSUE THREAD

**Issue by jarobin** [rvaser/sift4g#10]
Hi Robert,

I am attempting to create a SIFT database by using Pauline's SIFT4G_Create_Genomic_DB method. I am working with a genome assembly and annotation from RefSeq (fasta: GCF_008728515.1_Panubis1.0_genomic.fna.gz, annotation: GCF_008728515.1_Panubis1.0_genomic.gtf.gz, both available at https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/008/728/515/GCF_008728515.1_Panubis1.0). A failure is occurring during the SIFT4G alignment step:

start siftsharp, getting the alignments
~/programs/sift/sift4g/bin/sift4g -d ~/programs/sift/SIFT_databases/uniref90.fasta -q ~/programs/sift/SIFT_databases/GCF_008728515.1_Panubis1.0/all_prot.fasta --subst ~/programs/sift/SIFT_databases/GCF_008728515.1_Panubis1.0/subst --out ~/programs/sift/SIFT_databases/GCF_008728515.1_Panubis1.0/SIFT_predictions --sub-results
** Checking query data and substitutions files **
* processing queries: 100.00/100.00% *

** Searching database for candidate sequences **
* processing database part 202 (size ~0.25 GB): 100.00/100.00% *

** Aligning queries with candidate sequences **
Alignment score and position are not consensus.72.50/100.00% **

The error looks to be the same as https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/issues/15, and is perhaps the same bug that you raised an issue for here: https://github.com/mkorpar/swsharp/issues/1.

Have you found a work-around for this problem? Is it possible, for instance, to alter the GTF file to remove the  sequence(s) triggering this error?

Thanks,
Jacqueline

P.S. I have successfully run the test examples for both sift4g and SIFT4G_Create_Genomic_DB, verifying that everything is installed correctly and apparently functional.

**Comment by rvaser** [comment]
Hi Jacqueline,
the bug is somewhere in the SSE alignment implementation that is a dependency of a dependency that SIFT4G relies on. You can bypass the error by replacing:

https://github.com/mkorpar/swsharp/blob/master/swsharp/src/cpu_module.c#L116 with
```cpp
if (0 && alignScoredPairSse(alignment, type, query, target, scorer, score) == 0) {
```

https://github.com/mkorpar/swsharp/blob/master/swsharp/src/cpu_module.c#L155 with
```cpp
if (0 && scorePairSse(&score, type, query, target, scorer) == 0) {
```

https://github.com/mkorpar/swsharp/blob/master/swsharp/src/cpu_module.c#L183 with
```cpp
if (0 && scoreDatabaseSse(scores, type, query, database, databaseLen, scorer) == 0) {
```

https://github.com/mkorpar/swsharp/blob/master/swsharp/src/cpu_module.c#L208-L209 with
```cpp
int status = 0; //scoreDatabasePartiallySse(scores, type, query, database, 
        //databaseLen, scorer, maxScore);
```

The mentioned file is `sift4g/vendor/swsharp/swsharp/src/cpu_module.c`. Run `make cpu` and it should work, but it will take longer to finish.

**Comment by jarobin** [comment]
Hi Robert,

This appears to have worked. Thank you!

For those interested, I first ran a test with a fasta file containing a single sequence that had completed successfully with the original, unmodified SIFT4G code to see how the runtime would be affected. Using the code modifications above, it took approximately twice as long to complete.

I then ran the database creation on a full 3 Gb genome using the modified SIFT4G code and the default number of threads (8). This took 9 days, and the max. memory usage was 84 Gb RAM. I was then able to use the created database for annotating a VCF file with the SIFT4G_Annotator (https://github.com/pauline-ng/SIFT4G_Annotator).

Thanks again, Robert.

**Comment by rvaser** [comment]
Hi Jacqueline,
thanks for getting back with the comparison. I am glad it worked this time around.

Best regards,
Robert

**Comment by Arynio** [comment]
Hi Robert,

I'm sorry for bumping this closed issue, but I ran into the problem described here and the proposed solution unfortunately didn't do the trick for me. I edited sift4g/vendor/swsharp/swsharp/src/cpu_module.c as indicated here https://github.com/rvaser/sift4g/issues/10#issuecomment-629128563 and then did `cd ..` and `make cpu` but I keep encountering the "Alignment score and position are not consensus." error message.

I've also followed indications from pauline-ng from https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/issues/15 and I made sure there are neither "X" nor "*" characters (nor duplicate entries) in the all_prot.fasta file.

Thank you very much in advance for any help or ideas that you may provide.

Best,

Daniel.

**Comment by rvaser** [comment]
Hi Daniel,
could you please provide me with the dataset it breaks on? I am not sure I can help you without it as the error is nested deeply in the dependency tree.

Best regards,
Robert

**Comment by Arynio** [comment]
Hi Robert,

Thanks for replying. Exactly which files would you need to look into this issue? Also would it be fine if I email them?

**Comment by rvaser** [comment]
Hi Daniel,
after commenting out the above mentioned parts, I am able to run Sift4g with your all_prot.fasta (without it gets killed (out of memory) probably due to a bug in ssw). I am rerunning now again for verification. Are you sure you commented everything out as described and recompiled afterwards?

Best regards,
Robert

**Comment by Arynio** [comment]
Dear Robert,

Thank you for testing it out. I just emailed you the edited version of cpu_module.c that I used. To recompile the programme I typed `make cpu` while in the following path: sift4g/vendor/swsharp/swsharp/src and didn't encounter any error (that I'm aware of). If the issue lies in the recompilation phase, do you think it would make sense to redownload the programme, replace cpu_module.c with the new version and then compile it?

**Comment by rvaser** [comment]
Hi Daniel,
the file you sent me is the same I am using (the 2nd run also finished successfully). Run `make` from sift4g root directory please (there is no Makefile in the path you provided). Do a `make clean` before `make` just in case.

Best regards,
Robert

**Comment by Arynio** [comment]
My bad, I meant sift4g/vendor/swsharp/swsharp/ path (because `make cpu` didn't work in the root directory). 

I just followed your latest suggestion while in the root directory and it did work, so I'll try once again to build my database and get back to you as soon as I have any (hopefully good) news! Thank you very much! ^^

Best,

Daniel.

**Comment by Arynio** [comment]
Dear Robert,

It worked fine this time around, so the issue indeed lay in the recompilation. Thank you very much for your great help!!!

Unfortunately the programme ran into some errors while populating the databases, and after it's done running, the folder singleRecords_with_scores stays empty. But I guess I shall report this as a new issue to Pauline?

Again, thank you. Best,

Daniel.

**Comment by rvaser** [comment]
Great to hear! Yes, please raise an issue on the other repository.

Best regards,
Robert
