### ISSUE TITLE
Precision of output tables

### ISSUE THREAD

**Issue by allydunham** [rvaser/sift4g#6]
Hi Robert,

The output .SIFTprediction tables contain scores rounded to 2 decimal places and it would be useful for my work to have more precision. I only occasionally use C++ but as far as I can tell this rounding is done just before writing the output table (e.g. the print_double functions at line 303 of sift_scores.cpp) with no option to change it.

Is there an important reason to round like this? or would I be able to simply change the precision when writing the output table and get more detailed scores?

Thanks,
Ally

**Comment by rvaser** [comment]
Hi Ally,
I have no idea why it is set to 2 decimal places. @pauline-ng, would any of the downstream analysis tools suffer if we increase the decimal places in SIFT scores?

Best regards,
Robert

P.s. You can manually change the part of the source code you pinpointed and recompile until you wait :)

**Comment by pauline-ng** [comment]
Hi @allydunham

SIFT was initially trained on a few thousand data points (I can't remember the exact number). I wouldn't advise rounding to more than the thousandths place (3 digits after the decimal place). You can change your sift_scores.cpp and recompile the code.

@rvaser -- Because this appears to be a rare request, I'd like to keep our current output the way it is and not change SIFT for now.

Thanks,
Pauline

**Comment by allydunham** [comment]
That's great, thank you both for the help. I recompiled and everything seems to be functional outputting more decimal places. 
Best,
Ally
